# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import python.user.user.user_pb2 as user__pb2


class UserCallStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AddUser = channel.unary_unary(
                '/UserCall/AddUser',
                request_serializer=user__pb2.AddUserRequest.SerializeToString,
                response_deserializer=user__pb2.UserReply.FromString,
                )
        self.RemoveUser = channel.unary_unary(
                '/UserCall/RemoveUser',
                request_serializer=user__pb2.RemoveUserRequest.SerializeToString,
                response_deserializer=user__pb2.UserReply.FromString,
                )
        self.GetAllClassesOfUser = channel.unary_unary(
                '/UserCall/GetAllClassesOfUser',
                request_serializer=user__pb2.GetAllClassesOfUserRequest.SerializeToString,
                response_deserializer=user__pb2.UserReply.FromString,
                )
        self.GetAllTeachers = channel.unary_unary(
                '/UserCall/GetAllTeachers',
                request_serializer=user__pb2.GetAllTeachersRequest.SerializeToString,
                response_deserializer=user__pb2.UserReply.FromString,
                )


class UserCallServicer(object):
    """Missing associated documentation comment in .proto file."""

    def AddUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemoveUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAllClassesOfUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAllTeachers(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_UserCallServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AddUser': grpc.unary_unary_rpc_method_handler(
                    servicer.AddUser,
                    request_deserializer=user__pb2.AddUserRequest.FromString,
                    response_serializer=user__pb2.UserReply.SerializeToString,
            ),
            'RemoveUser': grpc.unary_unary_rpc_method_handler(
                    servicer.RemoveUser,
                    request_deserializer=user__pb2.RemoveUserRequest.FromString,
                    response_serializer=user__pb2.UserReply.SerializeToString,
            ),
            'GetAllClassesOfUser': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAllClassesOfUser,
                    request_deserializer=user__pb2.GetAllClassesOfUserRequest.FromString,
                    response_serializer=user__pb2.UserReply.SerializeToString,
            ),
            'GetAllTeachers': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAllTeachers,
                    request_deserializer=user__pb2.GetAllTeachersRequest.FromString,
                    response_serializer=user__pb2.UserReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'UserCall', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class UserCall(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def AddUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/UserCall/AddUser',
            user__pb2.AddUserRequest.SerializeToString,
            user__pb2.UserReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RemoveUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/UserCall/RemoveUser',
            user__pb2.RemoveUserRequest.SerializeToString,
            user__pb2.UserReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetAllClassesOfUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/UserCall/GetAllClassesOfUser',
            user__pb2.GetAllClassesOfUserRequest.SerializeToString,
            user__pb2.UserReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetAllTeachers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/UserCall/GetAllTeachers',
            user__pb2.GetAllTeachersRequest.SerializeToString,
            user__pb2.UserReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
