# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from ..room import room_pb2 as room__pb2


class RoomCallStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AddRoom = channel.unary_unary(
                '/RoomCall/AddRoom',
                request_serializer=room__pb2.AddRoomRequest.SerializeToString,
                response_deserializer=room__pb2.RoomReply.FromString,
                )
        self.RemoveRoom = channel.unary_unary(
                '/RoomCall/RemoveRoom',
                request_serializer=room__pb2.RemoveRoomRequest.SerializeToString,
                response_deserializer=room__pb2.RoomReply.FromString,
                )
        self.GetAllRoomInfo = channel.unary_unary(
                '/RoomCall/GetAllRoomInfo',
                request_serializer=room__pb2.GetAllRoomInfoRequest.SerializeToString,
                response_deserializer=room__pb2.RoomReply.FromString,
                )


class RoomCallServicer(object):
    """Missing associated documentation comment in .proto file."""

    def AddRoom(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemoveRoom(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAllRoomInfo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RoomCallServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AddRoom': grpc.unary_unary_rpc_method_handler(
                    servicer.AddRoom,
                    request_deserializer=room__pb2.AddRoomRequest.FromString,
                    response_serializer=room__pb2.RoomReply.SerializeToString,
            ),
            'RemoveRoom': grpc.unary_unary_rpc_method_handler(
                    servicer.RemoveRoom,
                    request_deserializer=room__pb2.RemoveRoomRequest.FromString,
                    response_serializer=room__pb2.RoomReply.SerializeToString,
            ),
            'GetAllRoomInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAllRoomInfo,
                    request_deserializer=room__pb2.GetAllRoomInfoRequest.FromString,
                    response_serializer=room__pb2.RoomReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'RoomCall', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class RoomCall(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def AddRoom(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/RoomCall/AddRoom',
            room__pb2.AddRoomRequest.SerializeToString,
            room__pb2.RoomReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RemoveRoom(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/RoomCall/RemoveRoom',
            room__pb2.RemoveRoomRequest.SerializeToString,
            room__pb2.RoomReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetAllRoomInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/RoomCall/GetAllRoomInfo',
            room__pb2.GetAllRoomInfoRequest.SerializeToString,
            room__pb2.RoomReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
