# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: room.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nroom.proto\"L\n\x0e\x41\x64\x64RoomRequest\x12\x11\n\troom_name\x18\x01 \x01(\t\x12\x13\n\x0broom_length\x18\x02 \x01(\x05\x12\x12\n\nroom_width\x18\x03 \x01(\x05\"$\n\x11RemoveRoomRequest\x12\x0f\n\x07room_id\x18\x01 \x01(\x05\"(\n\x15GetAllRoomInfoRequest\x12\x0f\n\x07room_id\x18\x01 \x01(\x05\"`\n\tRoomReply\x12\x14\n\x07message\x18\x01 \x01(\tH\x00\x88\x01\x01\x12\x12\n\x05\x65rror\x18\x02 \x01(\tH\x01\x88\x01\x01\x12\x13\n\x0bstatus_code\x18\x03 \x01(\x05\x42\n\n\x08_messageB\x08\n\x06_error2\x9c\x01\n\x08RoomCall\x12(\n\x07\x41\x64\x64Room\x12\x0f.AddRoomRequest\x1a\n.RoomReply\"\x00\x12.\n\nRemoveRoom\x12\x12.RemoveRoomRequest\x1a\n.RoomReply\"\x00\x12\x36\n\x0eGetAllRoomInfo\x12\x16.GetAllRoomInfoRequest\x1a\n.RoomReply\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'room_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ADDROOMREQUEST._serialized_start=14
  _ADDROOMREQUEST._serialized_end=90
  _REMOVEROOMREQUEST._serialized_start=92
  _REMOVEROOMREQUEST._serialized_end=128
  _GETALLROOMINFOREQUEST._serialized_start=130
  _GETALLROOMINFOREQUEST._serialized_end=170
  _ROOMREPLY._serialized_start=172
  _ROOMREPLY._serialized_end=268
  _ROOMCALL._serialized_start=271
  _ROOMCALL._serialized_end=427
# @@protoc_insertion_point(module_scope)
