# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import python.seating.seating.seating_pb2 as seating__pb2


class SeatingCallStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AddChairToSeatingArrangement = channel.unary_unary(
                '/SeatingCall/AddChairToSeatingArrangement',
                request_serializer=seating__pb2.AddChairToSeatingArrangementRequest.SerializeToString,
                response_deserializer=seating__pb2.SeatingReply.FromString,
                )
        self.RemoveChairFromSeatingArrangement = channel.unary_unary(
                '/SeatingCall/RemoveChairFromSeatingArrangement',
                request_serializer=seating__pb2.RemoveChairFromSeatingArrangementRequest.SerializeToString,
                response_deserializer=seating__pb2.SeatingReply.FromString,
                )
        self.GetStudentFromChair = channel.unary_unary(
                '/SeatingCall/GetStudentFromChair',
                request_serializer=seating__pb2.GetStudentFromChairRequest.SerializeToString,
                response_deserializer=seating__pb2.SeatingReply.FromString,
                )


class SeatingCallServicer(object):
    """Missing associated documentation comment in .proto file."""

    def AddChairToSeatingArrangement(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemoveChairFromSeatingArrangement(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStudentFromChair(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SeatingCallServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AddChairToSeatingArrangement': grpc.unary_unary_rpc_method_handler(
                    servicer.AddChairToSeatingArrangement,
                    request_deserializer=seating__pb2.AddChairToSeatingArrangementRequest.FromString,
                    response_serializer=seating__pb2.SeatingReply.SerializeToString,
            ),
            'RemoveChairFromSeatingArrangement': grpc.unary_unary_rpc_method_handler(
                    servicer.RemoveChairFromSeatingArrangement,
                    request_deserializer=seating__pb2.RemoveChairFromSeatingArrangementRequest.FromString,
                    response_serializer=seating__pb2.SeatingReply.SerializeToString,
            ),
            'GetStudentFromChair': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStudentFromChair,
                    request_deserializer=seating__pb2.GetStudentFromChairRequest.FromString,
                    response_serializer=seating__pb2.SeatingReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'SeatingCall', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class SeatingCall(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def AddChairToSeatingArrangement(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/SeatingCall/AddChairToSeatingArrangement',
            seating__pb2.AddChairToSeatingArrangementRequest.SerializeToString,
            seating__pb2.SeatingReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RemoveChairFromSeatingArrangement(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/SeatingCall/RemoveChairFromSeatingArrangement',
            seating__pb2.RemoveChairFromSeatingArrangementRequest.SerializeToString,
            seating__pb2.SeatingReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetStudentFromChair(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/SeatingCall/GetStudentFromChair',
            seating__pb2.GetStudentFromChairRequest.SerializeToString,
            seating__pb2.SeatingReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
